baseUrl: "https://www.bpesquet.fr"
title: "Baptiste Pesquet"
theme: "anubis"
paginate: 10
disqusShortname:
googleAnalytics: "G-4DNVMNCRYK"
enableRobotsTXT: true
enableGitInfo: true
defaultContentLanguage: en

languages:
  en:
    languageName: English
    weight: 1
    menu:
      main:
        - name: Teaching
          url: /teaching
          weight: 1
        - name: Research
          url: /research
          weight: 2

params:
  author: "Baptiste Pesquet"
  email: bpesquet [at] gmail [dot] com # used for microformats
  description: "Baptiste Pesquet's personal website"
  dateFormat: "January 2, 2006"
  # customCSS:
  #  - css/my.css
  mainSections:
    - posts
  paginationSinglePost: true
  style: auto # light-without-switcher
  readMore: false
  toc: true # display Table of Contents
  social:
    - id: email
      name: bpesquet [at] gmail [dot] com
    - id: github
      name: bpesquet
    - id: twitter
      name: bpesquet
    - id: youtube
      name: ../@bpesquet # workaround since Anubis prepends "c/" to the YouTube channel name (format for renamed channels)
    - id: linkedin
      name: bpesquet

taxonomies:
  tag: "tags"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown

  highlight:
    lineNos: false
    style: fruity # https://xyproto.github.io/splash/docs/all.html
    tabWidth: 4
