languageCode: "en-us"
baseUrl: "https://www.bpesquet.fr"
title: "👨‍💻 Baptiste Pesquet"
theme: "anubis"
paginate: 10
disqusShortname: 
googleAnalytics: "UA-39897312-4"
enableRobotsTXT: true

menu:
  main:
  - identifier: cv
    name: CV
    title: CV
    url: http://cv.bpesquet.fr/CV_BaptistePesquet.pdf
    weight: 1
  - identifier: posts
    name: Posts
    title: Posts 
    url: /posts
    weight: 2
  - identifier: teaching
    name: Teaching
    title: Teaching
    url: /teaching
    weight: 3
  - identifier: freelancing
    name: Freelancing
    title: Freelancing
    url: /freelancing
    weight: 4

params:
  author: "Baptiste Pesquet"
  description: "Baptiste Pesquet's personal website"
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  customJS:
    - js/main.js # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light-without-switcher
  readMore: false
  style: "auto"

taxonomies: 
  tag: "tags"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown

  highlight:
    lineNos: false
    style: fruity # https://xyproto.github.io/splash/docs/all.html
    tabWidth: 4