languageCode: "en-us"
baseUrl: "https://bpesquet.github.io"
title: "👨‍💻 Baptiste Pesquet"
theme: "anubis"
paginate: 10
disqusShortname: 
googleAnalytics: 
enableRobotsTXT: true

menu:
  main:
  - identifier: cv
    name: CV
    title: CV
    url: /posts/
    weight: 1
  - identifier: teaching
    name: Teaching
    title: Teaching
    url: /teaching/current
    weight: 2

params:
  author: "Baptiste Pesquet"
  description: "Baptiste Pesquet's personal website"
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  customJS:
    - js/main.js # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light-without-switcher
  readMore: false

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown