languageCode: "en-us"
baseUrl: "https://www.bpesquet.fr"
title: "👨‍💻 Baptiste Pesquet"
theme: "anubis"
paginate: 10
disqusShortname:
googleAnalytics: "UA-39897312-4"
enableRobotsTXT: true
enableGitInfo: true

menu:
  main:
    - identifier: cv
      name: CV
      title: CV
      url: http://cv.bpesquet.fr/CV_BaptistePesquet.pdf
      weight: 1
    - identifier: teaching
      name: Teaching
      title: Teaching
      url: /teaching
      weight: 2
    - identifier: posts
      name: Blog
      title: Blog
      url: /posts
      weight: 3
    - identifier: freelancing
      name: Freelancing
      title: Freelancing
      url: /freelancing
      weight: 4

params:
  author: "Baptiste Pesquet"
  email: bpesquet [at] gmail [dot] com # used for microformats
  description: "Baptiste Pesquet's personal website"
  dateFormat: "January 2, 2006"
  customCSS:
    - css/my.css
  paginationSinglePost: true
  style: auto # light-without-switcher
  readMore: false
  social:
    - id: email
      name: bpesquet [at] gmail [dot] com
    - id: github
      name: bpesquet
    - id: twitter
      name: bpesquet
    - id: youtube
      name: ../channel/UCtcjS2WTFBxwLlkiJYj_mtQ # workaround since Anubis prepends "c/" to the YouTube channel name (format for renamed channels)
    - id: linkedin
      name: bpesquet

taxonomies:
  tag: "tags"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown

  highlight:
    lineNos: false
    style: fruity # https://xyproto.github.io/splash/docs/all.html
    tabWidth: 4
