baseUrl: "https://www.bpesquet.fr"
title: "Baptiste Pesquet"
theme: "anubis"
paginate: 10
disqusShortname:
googleAnalytics: "G-4DNVMNCRYK"
enableRobotsTXT: true
enableGitInfo: true

menu:
  main:
    - name: Short bio
      pageRef: /bio
      weight: 1
    - name: Teaching
      pageRef: /teaching
      weight: 2
    - name: Research
      pageRef: /research
      weight: 3
    - name: Blog
      pageRef: /posts
      weight: 4

params:
  author: "Baptiste Pesquet"
  email: bpesquet [at] gmail [dot] com # used for microformats
  description: "Baptiste Pesquet's professional website"
  dateFormat: "January 2, 2006"
  customCSS:
   - css/my.css
  # mainSections: [ "posts" ] # which sections should be on index/main page
  paginationSinglePost: true
  style: auto # light-without-switcher
  readMore: false
  toc: true # display Table of Contents
  mathjax: true
  social:
    - id: email
      name: bpesquet [at] gmail [dot] com
    - id: github
      name: bpesquet
    - id: google-scholar
      url: "https://scholar.google.fr/citations?hl=fr&user=0KJ7JkMAAAAJ"
    - id: Linkedin
      url: "https://www.linkedin.com/in/bpesquet"
    - id: bluesky
      url: "https://bsky.app/profile/bpesquet.bsky.social"
    - id: youtube
      name: ../@bpesquet # workaround since Anubis prepends "c/" to the YouTube channel name (format for renamed channels)
    
taxonomies:
  tag: "tags"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown

  highlight:
    lineNos: false
    style: fruity # https://xyproto.github.io/splash/docs/all.html
    tabWidth: 4
